version: '3.8'

services:
  mindsdb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xplaincrypto-mindsdb
    ports:
      - "47334:47334"  # HTTP API
      - "47335:47335"  # MySQL API
    environment:
      # API Keys from .env file
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - DUNE_API_KEY=${DUNE_API_KEY}
      - WHALE_ALERTS_API_KEY=${WHALE_ALERTS_API_KEY}
      - DEFILLAMA_API_KEY=${DEFILLAMA_API_KEY}
      - BLOCKCHAIN_API_KEY=${BLOCKCHAIN_API_KEY}
      # Optional API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      # MindsDB Configuration
      - MINDSDB_DEFAULT_PROJECT=${MINDSDB_DEFAULT_PROJECT:-xplaincrypto}
      - MINDSDB_LOG_LEVEL=${MINDSDB_LOG_LEVEL:-INFO}
      # Database connections
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mindsdb_crypto
      - POSTGRES_USER=mindsdb
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - mindsdb_data:/mindsdb/var
      - ./logs:/mindsdb/logs
      - ./config:/mindsdb/config
    networks:
      - xplaincrypto_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:47334/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: xplaincrypto-postgres
    environment:
      POSTGRES_DB: mindsdb_crypto
      POSTGRES_USER: mindsdb
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d
    networks:
      - xplaincrypto_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mindsdb"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: xplaincrypto-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - xplaincrypto_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  mindsdb_data:
    driver: local
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  xplaincrypto_network:
    driver: bridge