
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindsdb
  namespace: mindsdb-crypto
  labels:
    app: mindsdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mindsdb
  template:
    metadata:
      labels:
        app: mindsdb
    spec:
      containers:
      - name: mindsdb
        image: mindsdb/mindsdb-crypto:latest
        ports:
        - containerPort: 47334
          name: http
        - containerPort: 47335
          name: mysql
        - containerPort: 47336
          name: mongodb
        - containerPort: 47337
          name: mcp
        env:
        - name: MINDSDB_STORAGE_PATH
          value: "/opt/mindsdb"
        - name: MINDSDB_CONFIG_PATH
          value: "/opt/mindsdb/config/config.json"
        - name: MINDSDB_APIS
          value: "http,mysql,mongodb,mcp"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mindsdb"
        - name: POSTGRES_USER
          value: "mindsdb"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: postgres-password
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: redis-password
        - name: MINDSDB_MCP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: mcp-access-token
        - name: COINMARKETCAP_API_KEY
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: coinmarketcap-api-key
        - name: DEFILLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: defillama-api-key
        - name: COINGECKO_API_KEY
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: coingecko-api-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mindsdb-secrets
              key: openai-api-key
        volumeMounts:
        - name: mindsdb-storage
          mountPath: /opt/mindsdb
        - name: config
          mountPath: /opt/mindsdb/config
        - name: agents
          mountPath: /opt/mindsdb/agents
        livenessProbe:
          httpGet:
            path: /api/status
            port: 47334
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/status
            port: 47334
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: mindsdb-storage
        persistentVolumeClaim:
          claimName: mindsdb-pvc
      - name: config
        configMap:
          name: mindsdb-config
      - name: agents
        configMap:
          name: mindsdb-agents

---
apiVersion: v1
kind: Service
metadata:
  name: mindsdb-service
  namespace: mindsdb-crypto
spec:
  selector:
    app: mindsdb
  ports:
  - name: http
    port: 47334
    targetPort: 47334
  - name: mysql
    port: 47335
    targetPort: 47335
  - name: mongodb
    port: 47336
    targetPort: 47336
  - name: mcp
    port: 47337
    targetPort: 47337
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindsdb-pvc
  namespace: mindsdb-crypto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mindsdb-hpa
  namespace: mindsdb-crypto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mindsdb
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
